#!/bin/bash
set -e

# start database
service postgresql-9.2 start

#create chado user and database
PGPASSWORD=admin createuser -U admin -d -E -l chado
PGPASSWORD=admin psql -U admin -c "ALTER ROLE chado PASSWORD 'chado'"
PGPASSWORD=chado createdb -U chado -h 127.0.0.1 chado
PGPASSWORD=chado psql -q -U chado -h 127.0.0.1 -f /chado/schema.sql chado

service postgresql-9.2 stop



