#!/bin/bash
set -e

# setup database
service postgresql-9.2 initdb
service postgresql-9.2 start


# account setup
su postgres -s /usr/bin/psql -- -U postgres -c "ALTER ROLE postgres WITH ENCRYPTED PASSWORD 'postgres'"
su postgres -s /usr/bin/createuser -- -U postgres -d -E -l -r admin
su postgres -s /usr/bin/psql -- -U postgres -c "ALTER ROLE admin PASSWORD 'admin'"

# create admin database
PGPASSWORD=admin createdb -U admin admin


