#!/bin/bash

# install postgresql(9.2)
echo 'NETWORKING=yes' > /etc/sysconfig/network
cp /config/CentOS-Base.repo /etc/yum.repos.d/
yum -y --exclude=upstart\* update
yum -y --exclude=upstart\* upgrade
rpm -ivh http://yum.postgresql.org/9.2/redhat/rhel-6-x86_64/pgdg-centos92-9.2-6.noarch.rpm
yum -y install postgresql92-server postgresql92-contrib rsync


