#!/bin/bash

FOLDER=/var/lib/pgsql/9.2
BACKUP=${FOLDER}/backups
DATA=${FOLDER}/data
BACKUPTOOL=/usr/pgsql-9.2/bin/pg_basebackup

OPTSPEC="i:u:p:"

ip=
user=
password=

while getopts $OPTSPEC option
do
    case $option in
        i) ip=$OPTARG
            ;;
        u) user=$OPTARG
            ;;
        p) password=$OPTARG
            ;;
    esac
done

if [ $OPTIND -eq 7 ]
then
    read -r -d '' recovery <<EOR

    standby_mode = 'on'
    primary_conninfo = 'host=$ip port=5432 user=$user password=$password'

    EOR

    su postgres -s /bin/echo -- "$recovery" > ${DATA}/recovery.conf

    if [ ! -e $BACKUP ]; then 
        su postgres -s /bin/mkdir -- -p $BACKUP
    fi

    PGPASSWORD=$password su postgres -s $BACKUPTOOL -- -h $ip -U $user -c fast -P -D $BACKUP
    su postgres -s /usr/bin/rsync -- -avP --exclude '*.conf'  --exclude pg_xlog --exclude 'postmaster.pid' $BACKUP/  $DATA/
else
    echo '!!! Expect options not passed'
    exit 1
fi



